import type { KdpListingPayload } from "@/lib/kdp/generate-kdp-listing";

export function formatKdpListingMarkdown(
  bookTitle: string,
  data: KdpListingPayload,
): string {
  const kw = data.keywords.map((k, i) => `${i + 1}. ${k}`).join("\n");
  const titles = data.titleSuggestions.map((t, i) => `${i + 1}. ${t}`).join("\n");
  const subs = data.subtitleSuggestions.map((t, i) => `${i + 1}. ${t}`).join("\n");

  return `# KDP listing metadata — ${bookTitle}

AI-assisted draft — **edit for accuracy, voice, and compliance** before pasting into KDP.

---

## Title ideas (pick one for the KDP Title field)

${titles}

_Current working title in ChapterAI: “${bookTitle}”_

---

## Subtitle ideas (optional)

${subs}

---

## Amazon book description

Paste into KDP **Description** (plain text; KDP may accept limited formatting—follow their current rules).

${data.amazonDescription}

---

## Seven keywords

KDP provides **7 keyword boxes**. Paste **one line per box** (not comma-separated in one box).

${kw}

---

## About the author (two sentences)

For **paperback back cover**, **Author Central**, or your website. Third person.

${data.aboutTheAuthorTwoSentences}

---

## Back of the book (paperback)

Marketing blurb for the **back cover** (trim to fit your cover designer’s layout).

${data.backCoverPaperbackBlurb}

---

## Category hints

Use these as a guide when picking **two categories** in KDP—they must match options in KDP’s picker.

1. ${data.bisacCategoryHints[0]}
2. ${data.bisacCategoryHints[1]}

---

*Generated by ChapterAI. You are responsible for final copy and KDP compliance.*
`;
}
